language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - npm run build
cache:
  directories:
    - "node_modules"
addons:
  ssh_known_hosts: anniekostolany.com
env:
  - REMOTE_DIR_STAGE=~/web/staging.anniekostolany.com/public_html
  - REMOTE_DIR_PROD=~/web/anniekostolany.com/public_html
  - REMOTE_HOST=anniekostolany.com
before_deploy:
  - echo '$SSH_KEY' > /tmp/deploy_rsa
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  # deploy to the staging environment
  - provider: script
    skip_cleanup: true
    script: rsync -azP $TRAVIS_BUILD_DIR/out $SSH_STAGE_USER@$REMOTE_HOST:$REMOTE_DIR_STAGE
    on:
      branch: staging
  # deploy to production
  - provider: script
    skip_cleanup: true
    script: rsync -azP $TRAVIS_BUILD_DIR/out $SSH_PROD_USER@$REMOTE_HOST:$REMOTE_DIR_PROD
    on:
      branch: master
