language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - npm run build
cache:
  directories:
    - "node_modules"
deploy:
  # deploy to the staging environment
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh staging
    on:
      branch: staging
  # deploy to production
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh production
    on:
      branch: master
